enum Screens {
  MAIN_APP = 'MAIN_APP',

  // Common screens
  MAIN_SCREEN = 'MAIN_SCREEN',
  SHOP = 'SHOP_SCREEN',
  EVENTS = 'EVENTS_SCREEN',
  EVENTS_CONTENT = 'EVENTS_CONTENT_SCREEN',
  BONUSES = 'BONUSES_SCREEN',
  RESERVATION = 'RESERVATION_SCREEN',
  RESERVATION_SUCCESS = 'RESERVATION_SUCCESS_SCREEN',
  CONTACTS = 'CONTACTS_SCREEN',
  CART = 'CART_SCREEN',
  CART_SUCCESS = 'CART_SUCCESS_SCREEN',
}

export default Screens;
